version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: MySql5.7-CreditQ
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'localdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'localU'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: Asia/Kolkata
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db-creditq:/mnt/d/Docker/Mysql5.7
# Names our volume
volumes:
  my-db-creditq: