version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: MySql8-local
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'localdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'local'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: Asia/Kolkata
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
      # Where our data will be persisted
    volumes:
      - my8-db-local:/mnt/d/Docker/Mysql8
# Names our volume
volumes:
  my8-db-local: